language: java 
branches:
  only:
    - dev
addons:
 ssh_known_hosts: v1@dev.com
deploy:
 provider: "releases"  
 user: "Akvarel41" 
 password: "41akvarel"
 file: "Spektr"
 skip_cleanup: true
 on:
  tags: true

